import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '../lib/utils';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en-US'
      // className={cn(GeistSans.variable, GeistMono.variable, CalSans.variable, 'scroll-smooth')}
      className={cn('scroll-smooth')}
      suppressHydrationWarning>
      <body className='relative'>
        <Header />
        <main id='skip-nav' className='mx-auto mb-16 max-w-5xl px-5 py-24 sm:px-8'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
